version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_api
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    restart: always

volumes:
  postgres_data:

